### ISSUE TITLE
Geyser token access

### ISSUE THREAD

**Issue by p0st1t** [jito-labs/mev-bot#8]
Hello,

I have a private jito valitator on my vps. 

I would like to run the mev-bot, but i'm unable to get the geyser access_token.

I tried to contact the jito support but no answer since 5 days..

Is it possible to give me the right direction please?

Thanks a lot in advance, wishing you a very good day!

**Comment by codywyatt23** [comment]
Hi, message me on Telegram at https://t.me/codywyatt, I generate the `geyser_access_token `for you. I’ve successfully run the bot and hosted it on AWS. I’ve also tweaked the strategy for maximum gains.
